### ISSUE TITLE
Steam Resolution/FPS Options No Longer Work

### ISSUE THREAD

**Issue by KingJigglypuff** [riolubruh/YABDP4Nitro#131]
As mentioned in the title, custom stream resolutions/FPS don't seem to work with the latest version. I skimmed through the other issues to see what could be up, and it seems to be some sort of update? Though I've also noticed the plugin author working on a fix, so I'd just like to ask about specifics, if possible.

**Comment by K3NOXOFFICIAL** [comment]
@KingJigglypuff Same thing here but I think it was also fixed with #119 in the update 3 hours ago.

**Comment by KingJigglypuff** [comment]
Is that so? I wonder what's wrong on my end then? Because I'm also on v4.7.2, and it's still not working.

**Comment by K3NOXOFFICIAL** [comment]
@KingJigglypuff Have you tried restarting BD and deleting the plugin and reinstalling it again?

Also If you have BDFDBv3.3.4 it may be interfering with it, tho I'm not really certain of it.
Tho turning the plugin off Deleting the config file for it and enabling it again fixed lots of problems for me.

**Comment by KingJigglypuff** [comment]
I've tried all of those, and I'm still stick with non Nitro stream settings.

**Comment by K3NOXOFFICIAL** [comment]
@KingJigglypuff Thats kinda weird, its working on my side of things
![github-discord](https://github.com/riolubruh/YABDP4Nitro/assets/46091052/eb5ccf39-50e3-4a90-84da-56bc966b686a)

**Comment by Earale** [comment]
Stream options are out for me, too. It seems to treat all streaming options (including 720p, 15fps, and 30fps) as nitro options and won't let me select them
![Discord_GVWYyFcmmk](https://github.com/riolubruh/YABDP4Nitro/assets/143066921/83c8d6ab-a493-4fe1-9777-ed15d59c0667)

**Comment by refriedfood** [comment]
Can confirm, just updated to 4.7.2 and they're all locked:
![img](https://ptpimg.me/r8n123.png)

**Comment by TerraFaster** [comment]
Go to the YABDP4Nitro plugin settings and **enable** "Change PremiumType" in "Miscellanous" category. This works for me.

**Comment by Sujan-G** [comment]
> Go to the YABDP4Nitro plugin settings and **enable** "Change PremiumType" in "Miscellanous" category. This works for me.

This worked for me

**Comment by KingJigglypuff** [comment]
> Go to the YABDP4Nitro plugin settings and **enable** "Change PremiumType" in "Miscellanous" category. This works for me.

Yep, that did it. I'll be closing this issue now.
