### ISSUE TITLE
(Bug?) Clips won't send

### ISSUE THREAD

**Issue by indianaliam1** [riolubruh/YABDP4Nitro#262]
hey, just letting you know i think they changed something in the way they send clips as now when i try any of my >10mb files they just flat out refuse to send now, giving an "Upload Failed" error. 

![Image](https://github.com/user-attachments/assets/84173eed-4cdd-4dd0-8844-48ad0fec4d6a)

(this was the same sort of thing as when they lowered the limit from 25 to 10 a few months ago and my discord hadn't caught up so didn't really know why it couldn't send the files, which is why i assume it's a bug.)

**Comment by ademCoin** [comment]
ME TOO !! i just send a picture but now with the plugin that dont work @**riolubruh @riolubruh**

**Comment by riolubruh** [comment]
yeah im aware of it, it's pretty frustrating. the main issue is that we are still relying on certain experiments being active which is a problem since experiments are known to not work alot of the time.

**Comment by riolubruh** [comment]
Should be fixed with [5.7.3](https://github.com/riolubruh/YABDP4Nitro/commit/9d30a4804b8184fe564e2200715c224652997b6b).

**Comment by indianaliam1** [comment]
it's still happening for me even on 5.7.3, am i uploading them wrong or something?
